# Generated by Django 5.2.14 on 2026-08-29 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0003_device_snmp_enabled_device_snmp_last_error_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopologyLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(choices=[('physical', 'Physical'), ('logical', 'Logical'), ('wan', 'WAN'), ('uplink', 'Uplink'), ('trunk', 'Trunk'), ('wireless', 'Wireless'), ('virtual', 'Virtual'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('discovery_source', models.CharField(choices=[('manual', 'Manual'), ('snmp', 'SNMP'), ('lldp', 'LLDP'), ('cdp', 'CDP'), ('import', 'Import')], default='manual', max_length=16)),
                ('confidence', models.PositiveSmallIntegerField(default=100)),
                ('status', models.CharField(db_index=True, default='unknown', max_length=16)),
                ('bandwidth_bps', models.PositiveBigIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topology_links', to='devices.site')),
                ('source_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_topology_links', to='devices.device')),
                ('source_interface', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_topology_links', to='devices.deviceinterface')),
                ('target_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_topology_links', to='devices.device')),
                ('target_interface', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_topology_links', to='devices.deviceinterface')),
            ],
            options={
                'indexes': [models.Index(fields=['site', 'status'], name='topology_to_site_id_b8d7aa_idx'), models.Index(fields=['source_device', 'target_device'], name='topology_to_source__c373b7_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('source_device', models.F('target_device')), _negated=True), name='topology_no_self_link'), models.UniqueConstraint(fields=('source_device', 'target_device', 'source_interface', 'target_interface'), name='unique_topology_link')],
            },
        ),
    ]
