# Generated by Django 5.2.7 on 2026-06-01 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('alert_type', models.CharField(choices=[('unknown_device', 'Unknown Device Detected'), ('device_offline', 'Device Offline'), ('high_bandwidth', 'High Bandwidth Usage'), ('suspicious_activity', 'Suspicious Activity'), ('failed_access', 'Repeated Failed Access Attempts')], max_length=32)),
                ('alert_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=16)),
                ('bandwidth_threshold_mbps', models.FloatField(blank=True, null=True)),
                ('offline_minutes', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, max_length=16)),
                ('alert_type', models.CharField(choices=[('unknown_device', 'Unknown Device Detected'), ('device_offline', 'Device Offline'), ('high_bandwidth', 'High Bandwidth Usage'), ('suspicious_activity', 'Suspicious Activity'), ('failed_access', 'Repeated Failed Access Attempts')], db_index=True, max_length=32)),
                ('message', models.TextField()),
                ('acknowledged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='devices.device')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
