# Generated by Django 5.2.14 on 2026-08-27 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_p1_alert_lifecycle'),
        ('devices', '0003_device_snmp_enabled_device_snmp_last_error_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='interface',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='devices.deviceinterface'),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='include_admin_down',
            field=models.BooleanField(default=False),
        ),
    ]
