# Generated by Django 5.2.14 on 2026-08-29 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_alert_interface_alertrule_include_admin_down'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='maintenance_suppressed',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
