# Generated by Django 5.2.14 on 2026-08-29 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_alert_maintenance_suppressed'),
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='maintenance_window',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppressed_alerts', to='operations.maintenancewindow'),
        ),
    ]
