# Generated by Django 5.2.7 on 2026-06-01 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_speed', models.FloatField(help_text='Mbps')),
                ('download_speed', models.FloatField(help_text='Mbps')),
                ('bandwidth_usage', models.FloatField(help_text='Total Mbps')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='traffic_samples', to='devices.device')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['device', 'timestamp'], name='traffic_tra_device__a45120_idx'), models.Index(fields=['timestamp'], name='traffic_tra_timesta_02a675_idx')],
            },
        ),
    ]
