# Generated by Django 5.2.14 on 2026-08-29 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('devices', '0003_device_snmp_enabled_device_snmp_last_error_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sites',
            field=models.ManyToManyField(blank=True, related_name='authorized_users', to='devices.site'),
        ),
    ]
