import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import apps.devices.models


class Migration(migrations.Migration):
    dependencies = [("devices", "0001_initial")]
    operations = [
        migrations.CreateModel(name="Organization", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(max_length=255)), ("code", models.SlugField(max_length=64, unique=True)), ("description", models.TextField(blank=True)), ("active", models.BooleanField(db_index=True, default=True)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True))]),
        migrations.CreateModel(name="Site", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(max_length=255)), ("code", models.SlugField(max_length=64)), ("description", models.TextField(blank=True)), ("timezone", models.CharField(default="UTC", max_length=64)), ("address", models.TextField(blank=True)), ("metadata", models.JSONField(blank=True, default=dict)), ("active", models.BooleanField(db_index=True, default=True)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("organization", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="sites", to="devices.organization"))], options={"indexes": [models.Index(fields=["organization", "active"], name="devices_sit_organiz_ac5a27_idx")], "constraints": [models.UniqueConstraint(fields=("organization", "code"), name="uniq_site_org_code")]}),
        migrations.CreateModel(name="NetworkSegment", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(max_length=255)), ("cidr", models.CharField(max_length=64, validators=[apps.devices.models.validate_safe_cidr])), ("vlan_id", models.PositiveIntegerField(blank=True, null=True)), ("description", models.TextField(blank=True)), ("monitoring_enabled", models.BooleanField(default=True)), ("discovery_enabled", models.BooleanField(default=False)), ("active", models.BooleanField(db_index=True, default=True)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("site", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="network_segments", to="devices.site"))], options={"indexes": [models.Index(fields=["site", "active", "monitoring_enabled"], name="devices_net_site_id_740067_idx")], "constraints": [models.UniqueConstraint(fields=("site", "cidr"), name="uniq_segment_site_cidr"), models.CheckConstraint(condition=models.Q(("vlan_id__isnull", True), ("vlan_id__lte", 4094), _connector="OR"), name="valid_vlan_id")]}),
        migrations.AddField(model_name="device", name="site", field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="devices", to="devices.site")),
        migrations.AddField(model_name="device", name="network_segment", field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="devices", to="devices.networksegment")),
        migrations.AddField(model_name="device", name="model", field=models.CharField(blank=True, max_length=255)),
        migrations.AddField(model_name="device", name="serial_number", field=models.CharField(blank=True, max_length=255)),
        migrations.AddField(model_name="device", name="operating_system", field=models.CharField(blank=True, max_length=255)),
        migrations.AddField(model_name="device", name="ipv6_address", field=models.GenericIPAddressField(blank=True, null=True, protocol="IPv6", unique=True)),
        migrations.AddField(model_name="device", name="device_type", field=models.CharField(choices=[("router", "Router"), ("switch", "Switch"), ("firewall", "Firewall"), ("server", "Server"), ("wireless_ap", "Wireless AP"), ("controller", "Controller"), ("printer", "Printer"), ("workstation", "Workstation"), ("iot", "IoT"), ("ups", "UPS"), ("storage", "Storage"), ("vm", "Virtual machine"), ("hypervisor", "Hypervisor"), ("unknown", "Unknown")], db_index=True, default="unknown", max_length=32)),
        migrations.AddField(model_name="device", name="criticality", field=models.CharField(choices=[("low", "Low"), ("medium", "Medium"), ("high", "High"), ("critical", "Critical")], default="medium", max_length=16)),
        migrations.AddField(model_name="device", name="lifecycle_status", field=models.CharField(db_index=True, default="active", max_length=32)),
        migrations.AddField(model_name="device", name="monitoring_enabled", field=models.BooleanField(db_index=True, default=True)),
        migrations.AddField(model_name="device", name="current_packet_loss", field=models.FloatField(blank=True, null=True)),
        migrations.AddField(model_name="device", name="uptime_seconds", field=models.PositiveBigIntegerField(blank=True, null=True)),
        migrations.AddField(model_name="device", name="consecutive_failures", field=models.PositiveIntegerField(default=0)),
        migrations.AddField(model_name="device", name="consecutive_successes", field=models.PositiveIntegerField(default=0)),
        migrations.AddField(model_name="device", name="first_discovered_at", field=models.DateTimeField(default=django.utils.timezone.now)),
        migrations.AddField(model_name="device", name="last_checked_at", field=models.DateTimeField(blank=True, db_index=True, null=True)),
        migrations.AddField(model_name="device", name="notes", field=models.TextField(blank=True)),
        migrations.AddField(model_name="device", name="updated_at", field=models.DateTimeField(default=django.utils.timezone.now), preserve_default=False),
        migrations.AlterField(model_name="device", name="updated_at", field=models.DateTimeField(auto_now=True)),
        migrations.AlterField(model_name="device", name="status", field=models.CharField(choices=[("online", "Online"), ("offline", "Offline"), ("unknown", "Unknown"), ("degraded", "Degraded"), ("maintenance", "Maintenance")], db_index=True, default="unknown", max_length=16)),
        migrations.AlterField(model_name="devicestatushistory", name="status", field=models.CharField(choices=[("online", "Online"), ("offline", "Offline"), ("unknown", "Unknown"), ("degraded", "Degraded"), ("maintenance", "Maintenance")], max_length=16)),
        migrations.AddIndex(model_name="device", index=models.Index(fields=["site", "status", "monitoring_enabled"], name="devices_dev_site_id_6bfa35_idx")),
        migrations.CreateModel(name="DeviceInterface", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("if_index", models.PositiveIntegerField()), ("name", models.CharField(max_length=255)), ("description", models.CharField(blank=True, max_length=500)), ("mac_address", models.CharField(blank=True, max_length=17)), ("admin_status", models.CharField(choices=[("up", "Up"), ("down", "Down"), ("testing", "Testing"), ("unknown", "Unknown")], default="unknown", max_length=16)), ("oper_status", models.CharField(choices=[("up", "Up"), ("down", "Down"), ("testing", "Testing"), ("unknown", "Unknown")], db_index=True, default="unknown", max_length=16)), ("speed_bps", models.PositiveBigIntegerField(blank=True, null=True)), ("mtu", models.PositiveIntegerField(blank=True, null=True)), ("interface_type", models.CharField(blank=True, max_length=64)), ("alias", models.CharField(blank=True, max_length=255)), ("inbound_octets", models.PositiveBigIntegerField(blank=True, null=True)), ("outbound_octets", models.PositiveBigIntegerField(blank=True, null=True)), ("inbound_errors", models.PositiveBigIntegerField(blank=True, null=True)), ("outbound_errors", models.PositiveBigIntegerField(blank=True, null=True)), ("inbound_discards", models.PositiveBigIntegerField(blank=True, null=True)), ("outbound_discards", models.PositiveBigIntegerField(blank=True, null=True)), ("utilization_in_pct", models.FloatField(blank=True, null=True)), ("utilization_out_pct", models.FloatField(blank=True, null=True)), ("last_polled_at", models.DateTimeField(blank=True, db_index=True, null=True)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("device", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="interfaces", to="devices.device"))], options={"indexes": [models.Index(fields=["device", "oper_status"], name="devices_dev_device__050b7d_idx")], "constraints": [models.UniqueConstraint(fields=("device", "if_index"), name="uniq_device_ifindex")]}),
        migrations.CreateModel(name="DeviceTelemetry", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("timestamp", models.DateTimeField(default=django.utils.timezone.now)), ("latency_ms", models.FloatField(blank=True, null=True)), ("packet_loss_pct", models.FloatField(blank=True, null=True)), ("cpu_pct", models.FloatField(blank=True, null=True)), ("memory_pct", models.FloatField(blank=True, null=True)), ("uptime_seconds", models.PositiveBigIntegerField(blank=True, null=True)), ("reachable", models.BooleanField()), ("source", models.CharField(default="unknown", max_length=32)), ("device", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="telemetry", to="devices.device"))], options={"ordering": ["timestamp"], "indexes": [models.Index(fields=["device", "timestamp"], name="devices_dev_device__06f7d4_idx")]}),
        migrations.CreateModel(name="InterfaceTelemetry", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("timestamp", models.DateTimeField(default=django.utils.timezone.now)), ("inbound_bps", models.FloatField(blank=True, null=True)), ("outbound_bps", models.FloatField(blank=True, null=True)), ("utilization_in_pct", models.FloatField(blank=True, null=True)), ("utilization_out_pct", models.FloatField(blank=True, null=True)), ("inbound_errors_delta", models.PositiveBigIntegerField(blank=True, null=True)), ("outbound_errors_delta", models.PositiveBigIntegerField(blank=True, null=True)), ("inbound_discards_delta", models.PositiveBigIntegerField(blank=True, null=True)), ("outbound_discards_delta", models.PositiveBigIntegerField(blank=True, null=True)), ("interface", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="telemetry", to="devices.deviceinterface"))], options={"ordering": ["timestamp"], "indexes": [models.Index(fields=["interface", "timestamp"], name="devices_int_interfa_aee155_idx")]}),
    ]
