# Generated by Django 5.2.14 on 2026-08-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_p1_monitoring_core'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='snmp_enabled',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='device',
            name='snmp_last_error_code',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='device',
            name='snmp_port',
            field=models.PositiveIntegerField(default=161),
        ),
        migrations.AddField(
            model_name='device',
            name='snmp_profile',
            field=models.CharField(default='generic', max_length=32),
        ),
        migrations.AddField(
            model_name='device',
            name='snmp_status',
            field=models.CharField(default='disabled', max_length=32),
        ),
        migrations.AddField(
            model_name='device',
            name='snmp_version',
            field=models.CharField(choices=[('2c', 'SNMPv2c'), ('3', 'SNMPv3')], default='3', max_length=8),
        ),
    ]
